---
- name: ensure X11Forwardig is disabled
  lineinfile: dest=/etc/ssh/sshd_config regexp=^X11Forwarding line="X11Forwarding no"
  notify: restart sshd
  
- name: disable root login over SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd
  
- name: disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}"  line="{{ item.line }}"
  with_items:
    - {regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no"}
    - {regexp: "^PasswordAuthentication", line: "PasswordAuthentication no"}
    - {regexp: "^UsePAM", line: "UsePAM no"}
  notify: restart sshd
